### ISSUE TITLE
List posible options for online donations (specially for Sri Lankans living in overseas)

### ISSUE THREAD

**Issue by danishka** [reliefsupports/reliefsupports.org-v1#10]
Create tab/page on "Online Donations"

Add "Donate via takas.lk and ICMD" 
URL: http://takas.lk/tag/product/list/tagId/196

Why we should add them?
Both takas.lk and ICMD was doing a great job since last year during disaster situations.
Sri Lankans who are living in overseas looking for opportunities to support victims and transferring small amount of cash is not worth after tax charges.

**Comment by namila** [comment]
U can also donate via Kapruka 
http://www.kapruka.com/contactUs/donate.jsp

**Comment by danishka** [comment]
@naveendw any comments on this?

**Comment by naveenmadhawa** [comment]
We can not trust Kapruka because of their previous experiences

**Comment by danishka** [comment]
fixed
