### ISSUE TITLE
Add Permalink for each event.

### ISSUE THREAD

**Issue by bhagyas** [reliefsupports/reliefsupports.org-v1#107]
Permalinks make it easier to share content through social media. It can also support feed notification types provided by Twitter and Facebook to receive more visibility on those networks.

Additional sharing buttons can be added for each permalink.

**Comment by ssudaraka** [comment]
This is a Work In Progress. Please refer to https://github.com/reliefsupports/reliefsupports.org/issues/3
Requesting to close this issue.

**Comment by bhagyas** [comment]
Provided additional feedback on #3.

**Comment by bhagyas** [comment]
Suggesting the below.

Twitter Card integration.
https://dev.twitter.com/cards/overview

Facebook Object Place Integration
https://developers.facebook.com/docs/reference/opengraph/object-type/place/

**Comment by kasunben** [comment]
This is done of now. So closing the issue :)
