### ISSUE TITLE
Issue Template markdown issues

### ISSUE THREAD

**Issue by CloudyPadmal** [reliefsupports/reliefsupports.org-v1#139]
## Issue Description
- The tick box `[] This issue is not already reported.` should be ` - [ ] This issue is not already reported.`
- `Environment issue Experienced In www.reliefsupports.org` should come in one line?

## Environment Issue Experienced In
www.reliefsupports.org

## Additional Information
Browser: Firefox v53
OS: Ubuntu 16.04

- [x] This issue is not already reported.

**Comment by kasunben** [comment]
@CloudyPadmal I am closing the issue since the issue has fixed as it seems. thanks!

**Comment by CloudyPadmal** [comment]
Thanks alot @thinkholic ! :blush:
