### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by pathumego** [reliefsupports/reliefsupports.org-v1#142]
Although the website mentions the project is Open Source, there is no license file in the repo and not clear what license the project is. I think it is important to have it in the repo before more people get on-board and project grows :) Everything seems compatible with GPL

@danishka @thinkholic

**Comment by kasunben** [comment]
We had a discussion about this  @danishka @naveendw
My vote for `MIT`.. @pathumego what do you think?

**Comment by kasunben** [comment]
SAHANA also use `MIT`... let's go with it.

**Comment by pathumego** [comment]
@thinkholic yep, it is more business friendly as well.

**Comment by kasunben** [comment]
@pathumego yeah! `GPL` sort of extreme in some cases :D

So, I am going to close this issue for now. If any disagreement we can open this later. :)
