### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by arunoda** [reliefsupports/reliefsupports.org-v1#18]
We need some ways to search the stuff in the forum.

**Comment by chamilad** [comment]
Expanding on this, IMO a somewhat broader approach would be to index on one side the providers, the items provided, and their locations and the required persons, required items, and their locations.

With this data, it should be somewhat possible to match requirements with providers by the provided items and how close their locations are. 

WDYT?

**Comment by danishka** [comment]
Nadeera is working on this ticket.

**Comment by danishka** [comment]
Deployed staging

**Comment by danishka** [comment]
Deployed on Production

**Comment by danishka** [comment]
Search bar is now available in home page.
Created #174 to enable search on donation and request pages.

**Comment by danishka** [comment]
@arunoda Thanks for filing this issue.
Please reopen this ticket if this fix not what you expected.
 CC: @chamilad
