### ISSUE TITLE
!!! Need developers. (Please read before you create an issue)

### ISSUE THREAD

**Issue by THPubs** [reliefsupports/reliefsupports.org-v1#20]
Guys, I think the developers of this app need help in coding. Before you create an issue or suggest a feature, please see whether you can implement it yourself and if you can, please clone the project and try it. It would be a great help for these guys.

**Comment by rajikaimal** [comment]
This message would be better transmitted if a `issue template` is created.

**Comment by harsha935** [comment]
Got it

**Comment by THPubs** [comment]
@rajikaimal Agreed!

**Comment by kasunben** [comment]
Since all are agreed :D I am closing this now :)
