### ISSUE TITLE
Clickable phone number links from mobile? <a href="tel:number">number</a> ?

### ISSUE THREAD

**Issue by kasunben** [reliefsupports/reliefsupports.org-v1#40]

**Comment by kokigit** [comment]
I will fix this. Could you please assign this to me

**Comment by thilinag** [comment]
Will have to consider the fact that this is a text field and users will add
numbers with wierd formats and will add multiple numbers in the same field.
For an start I think it will be useful to convert the numbers in
emergency-contacts page

**Comment by kokigit** [comment]
@thilinag ahh yeh that's true, I will revert them and push only emergency page then 👍

**Comment by kasunben** [comment]
Already fixed. So I am closing this now.
