### ISSUE TITLE
Relief Supports Blog

### ISSUE THREAD

**Issue by danishka** [reliefsupports/reliefsupports.org-v1#55]

**Comment by chamilad** [comment]
Why don't we use a static page generator and host that on github pages?

**Comment by arunoda** [comment]
I think we can directly use a Medium publication. No need to worry about anything.

**Comment by chanakaDe** [comment]
Guys, If you like ,i can give a wordpress blog. what you say ? Then it's so easy. Only need to login to admin and add any kind of posts

**Comment by danishka** [comment]
I just want to maintain a blog that give daily status on the situation.
 or write on any specific topic, and also make awareness on safety as well as environment protection. few people can handle this.

**Comment by chamilad** [comment]
+1 for a medium publication.

**Comment by danishka** [comment]
Created medium.com account 
https://medium.com/relief-supports/
