### ISSUE TITLE
Need Exception Handling to the app

### ISSUE THREAD

**Issue by kaviranga** [reliefsupports/reliefsupports.org-v1#79]
Still didn't found any laravel white/gray pages of death in this project . Laravel exceptions will be needed for some data conversion errors while submitting  the form data!

1.https://laravel.com/api/5.4/Illuminate/Exception/Handler.html 
2.https://laravel.com/docs/5.4/errors

**Comment by gayanhewa** [comment]
@kaviranga what if we get [sentry](https://sentry.io/for/open-source/) onboard its free for Open source projects and easy to debug all these unexpected issues

**Comment by kaviranga** [comment]
@gayanhewa It is a good idea .I haven't use this tool [sentry.io](https://sentry.io/for/open-source/) before. If we use this for the app how often the free accounts' validity time?

**Comment by kaviranga** [comment]
@gayanhewa @danishka @sanathks I've found this error on [http://reliefsupports.org/donations](http://reliefsupports.org/donations)
Need to fix the issue soon


![reliefsupports org_donations_error](https://cloud.githubusercontent.com/assets/6471174/26558623/e536464e-44c7-11e7-8534-a6442a9e28be.png)

**Comment by isuru4lk** [comment]
Issue is there
<img width="1204" alt="screen shot 2017-05-29 at 11 42 53 pm" src="https://cloud.githubusercontent.com/assets/8480671/26558767/dc83e06e-44c8-11e7-8aae-97cdde9b9196.png">

**Comment by kaviranga** [comment]
@isuru4lk Thanks for pointing that issue ...

**Comment by sanathks** [comment]
@kaviranga Yeah, Unfortunately, I don't have access. I'll try contact @danishka

**Comment by isuru4lk** [comment]
Seems like it's fixed now can't contact @danishka at this moment
