### ISSUE TITLE
FREE hosting

### ISSUE THREAD

**Issue by arunoda** [reliefsupports/reliefsupports.org-v1#9]
I'm working on a hosting company.
I can talk with them to give us FREE unlimited hosting.
Let me know, if you guys need it.

**Comment by danishka** [comment]
Highly appreciated your offer and as we discussed lets make plan to migrate to your environment within month or two.

Cheers!

**Comment by arunoda** [comment]
Nice. Just ping me.

**Comment by ssudaraka** [comment]
Guess we should close this issue.

**Comment by arunoda** [comment]
Yeah.
